version: '3.8'
services:
  redis_pelado:
    image: redis/redis-stack:latest
    container_name: redis_pelado
    volumes:
      - ./data/combined:/data 
    environment:
      - REDIS_ARGS=--save ''
    ports:
      - "6378:6379"
      - "8004:8001"

  redis_rdb:
    image: redis/redis-stack:latest
    container_name: redis_rdb
    volumes:
      - ./data/rdb:/data
    environment:
      - REDIS_ARGS=--save 900 1 --save 300 10 --save 60 10000 --dir /data
    ports:
      - "6379:6379"
      - "8001:8001"

  redis_aof:
    image: redis/redis-stack:latest
    container_name: redis_aof
    volumes:
      - ./data/aof:/data
    environment:
      - REDIS_ARGS=--save '' --appendonly yes --appendfsync everysec --dir /data
    ports:
      - "6380:6379"
      - "8002:8001"

  redis_combined:
    image: redis/redis-stack:latest
    container_name: redis_combined
    volumes:
      - ./data/combined:/data
    environment:
      - REDIS_ARGS=--save 900 1 --save 300 10 --save 60 10000 --appendonly yes --appendfsync everysec --dir /data
    ports:
      - "6381:6379"
      - "8003:8001"